robot:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  joint1_position_controller:
    type: position_controllers/JointPositionController
    joint: joint1
    pid: {p: 2000.0, i: 100, d: 5000.0}

  joint2_position_controller:
    type: position_controllers/JointPositionController
    joint: joint2
    pid: {p: 200000.0, i: 100, d: 500.0}

  joint3_position_controller:
    type: position_controllers/JointPositionController
    joint: joint3
    pid: {p: 20000.0, i: 100, d: 500.0}

  joint4_position_controller:
    type: position_controllers/JointPositionController
    joint: joint5
    pid: {p: 2000.0, i: 100, d: 500.0}

  joint5_position_controller:
    type: position_controllers/JointPositionController
    joint: joint6_1
    pid: {p: 2000.0, i: 100, d: 500.0}