robot:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  arm_controller:
    type: position_controllers/JointTrajectoryController
    joints:
      - joint1
      - joint2
      - joint3
      - joint5
    constraints:
      goal_time: 0.6
      stopped_velocity_tolerance: 0.05
      joint1: {trajectory: 0.1, goal: 0.1}
      joint2: {trajectory: 0.1, goal: 0.1}
      joint3: {trajectory: 0.1, goal: 0.1}
      joint5: {trajectory: 0.1, goal: 0.1}
    gains:
      joint1: {p: 10000, d: 500, i: 0, i_clamp: 1}
      joint2: {p: 10000, d: 150, i: 0, i_clamp: 1}
      joint3: {p: 50000, d: 150, i: 10, i_clamp: 50}
      joint5: {p: 50000, d: 150, i: 1, i_clamp: 25}
    stop_trajectory_duration: 0.5
    state_publish_rate:  25
    action_monitor_rate: 10

  grip_controller:
    type: position_controllers/JointTrajectoryController
    joints:
      - joint6_1
    constraints:
      goal_time: 0.6
      stopped_velocity_tolerance: 0.05
      joint6_1: {trajectory: 0.1, goal: 0.1}
    stop_trajectory_duration: 0.5
    state_publish_rate:  25
    action_monitor_rate: 10


  # joint1_position_controller:
  #   type: position_controllers/JointPositionController
  #   joint: joint1
  #   pid: {p: 2000.0, i: 100, d: 5000.0}

  # joint2_position_controller:
  #   type: position_controllers/JointPositionController
  #   joint: joint2
  #   pid: {p: 200000.0, i: 100, d: 500.0}

  # joint3_position_controller:
  #   type: position_controllers/JointPositionController
  #   joint: joint3
  #   pid: {p: 20000.0, i: 100, d: 500.0}

  # joint4_position_controller:
  #   type: position_controllers/JointPositionController
  #   joint: joint5
  #   pid: {p: 2000.0, i: 100, d: 500.0}

  # joint5_position_controller:
  #   type: position_controllers/JointPositionController
  #   joint: joint6_1
  #   pid: {p: 2000.0, i: 100, d: 500.0}


# position_controllers/JointPositionController
#   type: effort_controllers/JointTrajectoryController
#   joints:
#      - joint1
#      - joint2
#      - joint3
#      - joint5
#      - joint6_1
#   constraints:
#       goal_time: 0.6
#       stopped_velocity_tolerance: 0.05
#       joint1: {trajectory: 0.1, goal: 0.1}
#       joint2: {trajectory: 0.1, goal: 0.1}
#       joint3: {trajectory: 0.1, goal: 0.1}
#       joint5: {trajectory: 0.1, goal: 0.1}
#       joint6_1: {trajectory: 0.1, goal: 0.1}
#   gains:
#     joint1: {p: 10000, d: 500, i: 0, i_clamp: 1}
#     joint2: {p: 10000, d: 150, i: 0, i_clamp: 1}
#     joint3: {p: 50000, d: 150, i: 10, i_clamp: 50}
#     joint5: {p: 50000, d: 150, i: 1, i_clamp: 25}
#     joint6_1: {p: 100, d: 5, i: 0, i_clamp: 1}
#   stop_trajectory_duration: 0.5
#   state_publish_rate:  25
#   action_monitor_rate: 10